---

- name: Install
  become: yes
  apt: name=nginx state=latest 

- name: Start
  become: yes
  service: name=nginx state=started enabled=true

#- name: Supression de default.conf
 # become: yes
  #file: path=/etc/nginx/sites-enabled/default state=absent
  #notify: nginx reload

#- name: creation du dossier
 # become: yes
  #file: path=/home/{{ user }}/{{ domain }} state=directory owner={{ user }}

#- name: Lien vers www
 # become: yes
  #file: src=/home/{{ user }}/{{ domain }} dest=/var/www/{{ domain }} state=link

#- name: creation de la configuration nginx
 # template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ domain }}

#- name: Activation du domaine {{ domain }}
 # file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
  #notify: nginx reload